import type { Meal } from '../types';

export interface ParsedIngredient {
    name: string;
    quantity: string;
    originalText: string;
}

export interface MealPlanDay {
    day: string;
    meals: {
        type: string;
        name: string;
        ingredients?: { name: string; quantity: string; unit: string }[];
    }[];
}

/**
 * Extract all ingredients from meals
 */
export function extractIngredientsFromMeals(meals: Meal[]): string[] {
    const ingredients: string[] = [];

    for (const meal of meals) {
        if (meal.ingredients && meal.ingredients.length > 0) {
            for (const ing of meal.ingredients) {
                const qty = ing.quantity || '';
                const unit = ing.unit || '';
                const name = ing.name || '';

                if (name) {
                    const formatted = `${qty} ${unit} ${name}`.trim();
                    ingredients.push(formatted);
                }
            }
        }
    }

    return ingredients;
}

/**
 * Extract ingredients from meal plan JSON (generated by AI)
 */
export function extractIngredientsFromMealPlan(mealPlan: MealPlanDay[]): string[] {
    const ingredients: string[] = [];

    for (const day of mealPlan) {
        for (const meal of day.meals) {
            if (meal.ingredients) {
                for (const ing of meal.ingredients) {
                    const qty = ing.quantity || '';
                    const unit = ing.unit || '';
                    const name = ing.name || '';

                    if (name) {
                        const formatted = `${qty} ${unit} ${name}`.trim();
                        ingredients.push(formatted);
                    }
                }
            }
        }
    }

    return ingredients;
}

/**
 * Consolidate duplicate ingredients by name
 */
export function consolidateIngredients(ingredients: string[]): string[] {
    // Simple consolidation - group similar items
    const consolidated = new Map<string, string[]>();

    for (const ing of ingredients) {
        // Extract base name (remove quantities)
        const baseName = ing.replace(/^\d+[\s,./]*\d*\s*(g|kg|ml|l|un|unidade|xícara|colher|fatia)?\s*/i, '').toLowerCase().trim();

        if (!consolidated.has(baseName)) {
            consolidated.set(baseName, []);
        }
        consolidated.get(baseName)!.push(ing);
    }

    // Return unique list with first occurrence
    const result: string[] = [];
    for (const [, items] of consolidated) {
        result.push(items[0]);
    }

    return result;
}

/**
 * Generate shopping list prompt for AI
 */
export function buildShoppingListPrompt(ingredients: string[]): string {
    return `Você é um organizador de lista de compras. Receba a lista de ingredientes abaixo e agrupe-os por setor de supermercado.

INGREDIENTES:
${ingredients.map(i => `- ${i}`).join('\n')}

Retorne APENAS um JSON válido no seguinte formato (sem explicações):
{
  "Hortifruti": ["item1", "item2"],
  "Açougue": ["item1"],
  "Laticínios": ["item1"],
  "Mercearia": ["item1"],
  "Bebidas": ["item1"],
  "Congelados": ["item1"],
  "Padaria": ["item1"],
  "Outros": ["item1"]
}

Regras:
- Mantenha as quantidades originais quando disponíveis
- Remova categorias vazias
- Padronize nomes (ex: "2 bananas" em vez de "banana (2)")
- Use português brasileiro`;
}

/**
 * Parse AI response into ShoppingListCategory format
 */
export function parseShoppingListResponse(response: Record<string, string[]>): { category: string; items: { id: string; name: string; checked: boolean }[] }[] {
    const categories: { category: string; items: { id: string; name: string; checked: boolean }[] }[] = [];

    for (const [category, items] of Object.entries(response)) {
        if (items && items.length > 0) {
            categories.push({
                category,
                items: items.map((item, index) => ({
                    id: `${category}-${index}-${Date.now()}`,
                    name: item,
                    checked: false,
                })),
            });
        }
    }

    return categories;
}

/**
 * Save shopping list to localStorage
 */
export function saveShoppingListToStorage(categories: { category: string; items: { id: string; name: string; checked: boolean }[] }[]): void {
    localStorage.setItem('nutrismart_shopping_list', JSON.stringify({
        createdAt: new Date().toISOString(),
        categories,
    }));
}

/**
 * Load shopping list from localStorage
 */
export function loadShoppingListFromStorage(): { createdAt: string; categories: { category: string; items: { id: string; name: string; checked: boolean }[] }[] } | null {
    const stored = localStorage.getItem('nutrismart_shopping_list');
    if (!stored) return null;

    try {
        return JSON.parse(stored);
    } catch {
        return null;
    }
}

/**
 * Clear shopping list from localStorage
 */
export function clearShoppingListStorage(): void {
    localStorage.removeItem('nutrismart_shopping_list');
}
